
-- Add platforms_config field to automations table to store AI-generated API configurations
ALTER TABLE public.automations 
ADD COLUMN platforms_config JSONB DEFAULT NULL;

-- Add comment to explain the new field
COMMENT ON COLUMN public.automations.platforms_config IS 'Stores the complete API configurations for all platforms used in this automation, generated by AI';
